export const timeZones = [
  { id: 'baker-island', label: 'Baker Island', offset: -12.0, timeZone: 'Etc/GMT+12' },
  { id: 'pago-pago', label: 'Pago Pago', offset: -11.0, timeZone: 'Pacific/Pago_Pago' },
  { id: 'midway', label: 'Midway', offset: -11.0, timeZone: 'Pacific/Midway' },
  { id: 'niue', label: 'Niue', offset: -11.0, timeZone: 'Pacific/Niue' },
  { id: 'honolulu', label: 'Honolulu', offset: -10.0, timeZone: 'Pacific/Honolulu' },
  { id: 'papeete', label: 'Papeete', offset: -10.0, timeZone: 'Pacific/Tahiti' },
  { id: 'hilo', label: 'Hilo', offset: -10.0, timeZone: 'Pacific/Honolulu' },
  { id: 'marquesas-islands', label: 'Marquesas Islands', offset: -9.5, timeZone: 'Pacific/Marquesas' },
  { id: 'anchorage', label: 'Anchorage', offset: -9.0, timeZone: 'America/Anchorage' },
  { id: 'juneau', label: 'Juneau', offset: -9.0, timeZone: 'America/Juneau' },
  { id: 'adak', label: 'Adak', offset: -9.0, timeZone: 'America/Adak' },
  { id: 'los-angeles', label: 'Los Angeles', offset: -8.0, timeZone: 'America/Los_Angeles' },
  { id: 'seattle', label: 'Seattle', offset: -8.0, timeZone: 'America/Los_Angeles' },
  { id: 'vancouver', label: 'Vancouver', offset: -8.0, timeZone: 'America/Vancouver' },
  { id: 'denver', label: 'Denver', offset: -7.0, timeZone: 'America/Denver' },
  { id: 'phoenix', label: 'Phoenix', offset: -7.0, timeZone: 'America/Phoenix' },
  { id: 'calgary', label: 'Calgary', offset: -7.0, timeZone: 'America/Edmonton' },
  { id: 'chicago', label: 'Chicago', offset: -6.0, timeZone: 'America/Chicago' },
  { id: 'mexico-city', label: 'Mexico City', offset: -6.0, timeZone: 'America/Mexico_City' },
  { id: 'guatemala-city', label: 'Guatemala City', offset: -6.0, timeZone: 'America/Guatemala' },
  { id: 'new-york', label: 'New York', offset: -5.0, timeZone: 'America/New_York' },
  { id: 'toronto', label: 'Toronto', offset: -5.0, timeZone: 'America/Toronto' },
  { id: 'lima', label: 'Lima', offset: -5.0, timeZone: 'America/Lima' },
  { id: 'santiago', label: 'Santiago', offset: -4.0, timeZone: 'America/Santiago' },
  { id: 'la-paz', label: 'La Paz', offset: -4.0, timeZone: 'America/La_Paz' },
  { id: 'caracas', label: 'Caracas', offset: -4.0, timeZone: 'America/Caracas' },
  { id: 'st-johns', label: 'St. Johns', offset: -3.5, timeZone: 'America/St_Johns' },
  { id: 'buenos-aires', label: 'Buenos Aires', offset: -3.0, timeZone: 'America/Argentina/Buenos_Aires' },
  { id: 'sao-paulo', label: 'São Paulo', offset: -3.0, timeZone: 'America/Sao_Paulo' },
  { id: 'montevideo', label: 'Montevideo', offset: -3.0, timeZone: 'America/Montevideo' },
  { id: 'south-georgia', label: 'South Georgia', offset: -2.0, timeZone: 'Atlantic/South_Georgia' },
  { id: 'azores', label: 'Azores', offset: -1.0, timeZone: 'Atlantic/Azores' },
  { id: 'cape-verde', label: 'Cape Verde', offset: -1.0, timeZone: 'Atlantic/Cape_Verde' },
  { id: 'praia', label: 'Praia', offset: -1.0, timeZone: 'Atlantic/Cape_Verde' },
  { id: 'london', label: 'London', offset: 0.0, timeZone: 'Europe/London' },
  { id: 'dakar', label: 'Dakar', offset: 0.0, timeZone: 'Africa/Dakar' },
  { id: 'accra', label: 'Accra', offset: 0.0, timeZone: 'Africa/Accra' },
  { id: 'paris', label: 'Paris', offset: 1.0, timeZone: 'Europe/Paris' },
  { id: 'berlin', label: 'Berlin', offset: 1.0, timeZone: 'Europe/Berlin' },
  { id: 'madrid', label: 'Madrid', offset: 1.0, timeZone: 'Europe/Madrid' },
  { id: 'cairo', label: 'Cairo', offset: 2.0, timeZone: 'Africa/Cairo' },
  { id: 'athens', label: 'Athens', offset: 2.0, timeZone: 'Europe/Athens' },
  { id: 'johannesburg', label: 'Johannesburg', offset: 2.0, timeZone: 'Africa/Johannesburg' },
  { id: 'moscow', label: 'Moscow', offset: 3.0, timeZone: 'Europe/Moscow' },
  { id: 'nairobi', label: 'Nairobi', offset: 3.0, timeZone: 'Africa/Nairobi' },
  { id: 'riyadh', label: 'Riyadh', offset: 3.0, timeZone: 'Asia/Riyadh' },
  { id: 'tehran', label: 'Tehran', offset: 3.5, timeZone: 'Asia/Tehran' },
  { id: 'dubai', label: 'Dubai', offset: 4.0, timeZone: 'Asia/Dubai' },
  { id: 'baku', label: 'Baku', offset: 4.0, timeZone: 'Asia/Baku' },
  { id: 'yerevan', label: 'Yerevan', offset: 4.0, timeZone: 'Asia/Yerevan' },
  { id: 'kabul', label: 'Kabul', offset: 4.5, timeZone: 'Asia/Kabul' },
  { id: 'karachi', label: 'Karachi', offset: 5.0, timeZone: 'Asia/Karachi' },
  { id: 'tashkent', label: 'Tashkent', offset: 5.0, timeZone: 'Asia/Tashkent' },
  { id: 'yekaterinburg', label: 'Yekaterinburg', offset: 5.0, timeZone: 'Asia/Yekaterinburg' },
  { id: 'mumbai', label: 'Mumbai', offset: 5.5, timeZone: 'Asia/Kolkata' },
  { id: 'new-delhi', label: 'New Delhi', offset: 5.5, timeZone: 'Asia/Kolkata' },
  { id: 'colombo', label: 'Colombo', offset: 5.5, timeZone: 'Asia/Colombo' },
  { id: 'kathmandu', label: 'Kathmandu', offset: 5.75, timeZone: 'Asia/Kathmandu' },
  { id: 'dhaka', label: 'Dhaka', offset: 6.0, timeZone: 'Asia/Dhaka' },
  { id: 'almaty', label: 'Almaty', offset: 6.0, timeZone: 'Asia/Almaty' },
  { id: 'bishkek', label: 'Bishkek', offset: 6.0, timeZone: 'Asia/Bishkek' },
  { id: 'yangon', label: 'Yangon', offset: 6.5, timeZone: 'Asia/Yangon' },
  { id: 'cocos-islands', label: 'Cocos Islands', offset: 6.5, timeZone: 'Indian/Cocos' },
  { id: 'bangkok', label: 'Bangkok', offset: 7.0, timeZone: 'Asia/Bangkok' },
  { id: 'jakarta', label: 'Jakarta', offset: 7.0, timeZone: 'Asia/Jakarta' },
  { id: 'hanoi', label: 'Hanoi', offset: 7.0, timeZone: 'Asia/Ho_Chi_Minh' },
  { id: 'beijing', label: 'Beijing', offset: 8.0, timeZone: 'Asia/Shanghai' },
  { id: 'singapore', label: 'Singapore', offset: 8.0, timeZone: 'Asia/Singapore' },
  { id: 'perth', label: 'Perth', offset: 8.0, timeZone: 'Australia/Perth' },
  { id: 'eucla', label: 'Eucla', offset: 8.75, timeZone: 'Australia/Eucla' },
  { id: 'tokyo', label: 'Tokyo', offset: 9.0, timeZone: 'Asia/Tokyo' },
  { id: 'seoul', label: 'Seoul', offset: 9.0, timeZone: 'Asia/Seoul' },
  { id: 'pyongyang', label: 'Pyongyang', offset: 9.0, timeZone: 'Asia/Pyongyang' },
  { id: 'adelaide', label: 'Adelaide', offset: 9.5, timeZone: 'Australia/Adelaide' },
  { id: 'darwin', label: 'Darwin', offset: 9.5, timeZone: 'Australia/Darwin' },
  { id: 'sydney', label: 'Sydney', offset: 10.0, timeZone: 'Australia/Sydney' },
  { id: 'port-moresby', label: 'Port Moresby', offset: 10.0, timeZone: 'Pacific/Port_Moresby' },
  { id: 'hobart', label: 'Hobart', offset: 10.0, timeZone: 'Australia/Hobart' },
  { id: 'lord-howe-island', label: 'Lord Howe Island', offset: 10.5, timeZone: 'Australia/Lord_Howe' },
  { id: 'noumea', label: 'Nouméa', offset: 11.0, timeZone: 'Pacific/Noumea' },
  { id: 'honiara', label: 'Honiara', offset: 11.0, timeZone: 'Pacific/Guadalcanal' },
  { id: 'pohnpei', label: 'Pohnpei', offset: 11.0, timeZone: 'Pacific/Pohnpei' },
  { id: 'auckland', label: 'Auckland', offset: 12.0, timeZone: 'Pacific/Auckland' },
  { id: 'fiji', label: 'Fiji', offset: 12.0, timeZone: 'Pacific/Fiji' },
  { id: 'funafuti', label: 'Funafuti', offset: 12.0, timeZone: 'Pacific/Funafuti' },
  { id: 'chatham-islands', label: 'Chatham Islands', offset: 12.75, timeZone: 'Pacific/Chatham' },
  { id: 'nukualofa', label: 'Nukuʻalofa', offset: 13.0, timeZone: 'Pacific/Tongatapu' },
  { id: 'tokelau', label: 'Tokelau', offset: 13.0, timeZone: 'Pacific/Fakaofo' },
  { id: 'apia', label: 'Apia', offset: 13.0, timeZone: 'Pacific/Apia' },
  { id: 'kiritimati', label: 'Kiritimati', offset: 14.0, timeZone: 'Pacific/Kiritimati' },
];