export const timeZones = [
  { id: 'baker-island', label: 'Baker Island', offset: -12.0, timeZone: 'Baker Island Time' },
  { id: 'pago-pago', label: 'Pago Pago', offset: -11.0, timeZone: 'Samoa Standard Time' },
  { id: 'midway', label: 'Midway', offset: -11.0, timeZone: 'Samoa Standard Time' },
  { id: 'niue', label: 'Niue', offset: -11.0, timeZone: 'Samoa Standard Time' },
  { id: 'honolulu', label: 'Honolulu', offset: -10.0, timeZone: 'Hawaii-Aleutian Standard Time' },
  { id: 'papeete', label: 'Papeete', offset: -10.0, timeZone: 'Hawaii-Aleutian Standard Time' },
  { id: 'hilo', label: 'Hilo', offset: -10.0, timeZone: 'Hawaii-Aleutian Standard Time' },
  { id: 'marquesas-islands', label: 'Marquesas Islands', offset: -9.5, timeZone: 'Marquesas Time' },
  { id: 'anchorage', label: 'Anchorage', offset: -9.0, timeZone: 'Alaska Standard Time' },
  { id: 'juneau', label: 'Juneau', offset: -9.0, timeZone: 'Alaska Standard Time' },
  { id: 'adak', label: 'Adak', offset: -9.0, timeZone: 'Alaska Standard Time' },
  { id: 'los-angeles', label: 'Los Angeles', offset: -8.0, timeZone: 'Pacific Standard Time' },
  { id: 'seattle', label: 'Seattle', offset: -8.0, timeZone: 'Pacific Standard Time' },
  { id: 'vancouver', label: 'Vancouver', offset: -8.0, timeZone: 'Pacific Standard Time' },
  { id: 'denver', label: 'Denver', offset: -7.0, timeZone: 'Mountain Standard Time' },
  { id: 'phoenix', label: 'Phoenix', offset: -7.0, timeZone: 'Mountain Standard Time' },
  { id: 'calgary', label: 'Calgary', offset: -7.0, timeZone: 'Mountain Standard Time' },
  { id: 'chicago', label: 'Chicago', offset: -6.0, timeZone: 'Central Standard Time' },
  { id: 'mexico-city', label: 'Mexico City', offset: -6.0, timeZone: 'Central Standard Time' },
  { id: 'guatemala-city', label: 'Guatemala City', offset: -6.0, timeZone: 'Central Standard Time' },
  { id: 'new-york', label: 'New York', offset: -5.0, timeZone: 'Eastern Standard Time' },
  { id: 'toronto', label: 'Toronto', offset: -5.0, timeZone: 'Eastern Standard Time' },
  { id: 'lima', label: 'Lima', offset: -5.0, timeZone: 'Eastern Standard Time' },
  { id: 'santiago', label: 'Santiago', offset: -4.0, timeZone: 'Atlantic Standard Time' },
  { id: 'la-paz', label: 'La Paz', offset: -4.0, timeZone: 'Atlantic Standard Time' },
  { id: 'caracas', label: 'Caracas', offset: -4.0, timeZone: 'Atlantic Standard Time' },
  { id: 'st.-john's', label: 'St. John's', offset: -3.5, timeZone: 'Newfoundland Standard Time' },
  { id: 'buenos-aires', label: 'Buenos Aires', offset: -3.0, timeZone: 'Argentina/Brasilia Time' },
  { id: 'são-paulo', label: 'São Paulo', offset: -3.0, timeZone: 'Argentina/Brasilia Time' },
  { id: 'montevideo', label: 'Montevideo', offset: -3.0, timeZone: 'Argentina/Brasilia Time' },
  { id: 'south-georgia', label: 'South Georgia', offset: -2.0, timeZone: 'South Georgia Time' },
  { id: 'azores', label: 'Azores', offset: -1.0, timeZone: 'Azores Standard Time' },
  { id: 'cape-verde', label: 'Cape Verde', offset: -1.0, timeZone: 'Azores Standard Time' },
  { id: 'praia', label: 'Praia', offset: -1.0, timeZone: 'Azores Standard Time' },
  { id: 'london', label: 'London', offset: 0.0, timeZone: 'Greenwich Mean Time' },
  { id: 'dakar', label: 'Dakar', offset: 0.0, timeZone: 'Greenwich Mean Time' },
  { id: 'accra', label: 'Accra', offset: 0.0, timeZone: 'Greenwich Mean Time' },
  { id: 'paris', label: 'Paris', offset: 1.0, timeZone: 'Central European Time' },
  { id: 'berlin', label: 'Berlin', offset: 1.0, timeZone: 'Central European Time' },
  { id: 'madrid', label: 'Madrid', offset: 1.0, timeZone: 'Central European Time' },
  { id: 'cairo', label: 'Cairo', offset: 2.0, timeZone: 'Eastern European Time' },
  { id: 'athens', label: 'Athens', offset: 2.0, timeZone: 'Eastern European Time' },
  { id: 'johannesburg', label: 'Johannesburg', offset: 2.0, timeZone: 'Eastern European Time' },
  { id: 'moscow', label: 'Moscow', offset: 3.0, timeZone: 'Moscow/Arabian Time' },
  { id: 'nairobi', label: 'Nairobi', offset: 3.0, timeZone: 'Moscow/Arabian Time' },
  { id: 'riyadh', label: 'Riyadh', offset: 3.0, timeZone: 'Moscow/Arabian Time' },
  { id: 'tehran', label: 'Tehran', offset: 3.5, timeZone: 'Iran Standard Time' },
  { id: 'dubai', label: 'Dubai', offset: 4.0, timeZone: 'Gulf Standard Time' },
  { id: 'baku', label: 'Baku', offset: 4.0, timeZone: 'Gulf Standard Time' },
  { id: 'yerevan', label: 'Yerevan', offset: 4.0, timeZone: 'Gulf Standard Time' },
  { id: 'kabul', label: 'Kabul', offset: 4.5, timeZone: 'Afghanistan Time' },
  { id: 'karachi', label: 'Karachi', offset: 5.0, timeZone: 'Pakistan Standard Time' },
  { id: 'tashkent', label: 'Tashkent', offset: 5.0, timeZone: 'Pakistan Standard Time' },
  { id: 'yekaterinburg', label: 'Yekaterinburg', offset: 5.0, timeZone: 'Pakistan Standard Time' },
  { id: 'mumbai', label: 'Mumbai', offset: 5.5, timeZone: 'India Standard Time' },
  { id: 'new-delhi', label: 'New Delhi', offset: 5.5, timeZone: 'India Standard Time' },
  { id: 'colombo', label: 'Colombo', offset: 5.5, timeZone: 'India Standard Time' },
  { id: 'kathmandu', label: 'Kathmandu', offset: 5.75, timeZone: 'Nepal Time' },
  { id: 'dhaka', label: 'Dhaka', offset: 6.0, timeZone: 'Bangladesh Standard Time' },
  { id: 'almaty', label: 'Almaty', offset: 6.0, timeZone: 'Bangladesh Standard Time' },
  { id: 'bishkek', label: 'Bishkek', offset: 6.0, timeZone: 'Bangladesh Standard Time' },
  { id: 'yangon', label: 'Yangon', offset: 6.5, timeZone: 'Myanmar Time' },
  { id: 'cocos-islands', label: 'Cocos Islands', offset: 6.5, timeZone: 'Myanmar Time' },
  { id: 'bangkok', label: 'Bangkok', offset: 7.0, timeZone: 'Indochina Time' },
  { id: 'jakarta', label: 'Jakarta', offset: 7.0, timeZone: 'Indochina Time' },
  { id: 'hanoi', label: 'Hanoi', offset: 7.0, timeZone: 'Indochina Time' },
  { id: 'beijing', label: 'Beijing', offset: 8.0, timeZone: 'China Standard Time' },
  { id: 'singapore', label: 'Singapore', offset: 8.0, timeZone: 'China Standard Time' },
  { id: 'perth', label: 'Perth', offset: 8.0, timeZone: 'China Standard Time' },
  { id: 'eucla', label: 'Eucla', offset: 8.75, timeZone: 'Australian Central Western Time' },
  { id: 'tokyo', label: 'Tokyo', offset: 9.0, timeZone: 'Japan/Korea Standard Time' },
  { id: 'seoul', label: 'Seoul', offset: 9.0, timeZone: 'Japan/Korea Standard Time' },
  { id: 'pyongyang', label: 'Pyongyang', offset: 9.0, timeZone: 'Japan/Korea Standard Time' },
  { id: 'adelaide', label: 'Adelaide', offset: 9.5, timeZone: 'Australian Central Standard Time' },
  { id: 'darwin', label: 'Darwin', offset: 9.5, timeZone: 'Australian Central Standard Time' },
  { id: 'sydney', label: 'Sydney', offset: 10.0, timeZone: 'Australian Eastern Standard Time' },
  { id: 'port-moresby', label: 'Port Moresby', offset: 10.0, timeZone: 'Australian Eastern Standard Time' },
  { id: 'hobart', label: 'Hobart', offset: 10.0, timeZone: 'Australian Eastern Standard Time' },
  { id: 'lord-howe-island', label: 'Lord Howe Island', offset: 10.5, timeZone: 'Lord Howe Standard Time' },
  { id: 'nouméa', label: 'Nouméa', offset: 11.0, timeZone: 'Solomon/Vanuatu Time' },
  { id: 'honiara', label: 'Honiara', offset: 11.0, timeZone: 'Solomon/Vanuatu Time' },
  { id: 'pohnpei', label: 'Pohnpei', offset: 11.0, timeZone: 'Solomon/Vanuatu Time' },
  { id: 'auckland', label: 'Auckland', offset: 12.0, timeZone: 'New Zealand/Fiji Time' },
  { id: 'fiji', label: 'Fiji', offset: 12.0, timeZone: 'New Zealand/Fiji Time' },
  { id: 'funafuti', label: 'Funafuti', offset: 12.0, timeZone: 'New Zealand/Fiji Time' },
  { id: 'chatham-islands', label: 'Chatham Islands', offset: 12.75, timeZone: 'Chatham Islands Time' },
  { id: 'nukuʻalofa', label: 'Nukuʻalofa', offset: 13.0, timeZone: 'Tonga Time' },
  { id: 'tokelau', label: 'Tokelau', offset: 13.0, timeZone: 'Tonga Time' },
  { id: 'apia', label: 'Apia', offset: 13.0, timeZone: 'Tonga Time' },
  { id: 'kiritimati', label: 'Kiritimati', offset: 14.0, timeZone: 'Line Islands Time' },
];